### ISSUE TITLE
Blend circle actions

### ISSUE THREAD

**Issue by tessmichi** [dennisss/tansa#119]
If four drones are in the same circle but shifted by theta, we should use theta offsets so we can put them all into one jocs

**Comment by tessmichi** [comment]
This requires editing the parser as well as the jocs files themselves

**Comment by tessmichi** [comment]
Will keep in backlog for now since it wasnt prioritized in requirements doc,but will come to this if i have time

**Comment by abramowitzK** [comment]
This was added to jocs. CSV doesn't support offsets at this point since it would clutter the format too much and it's easier to just add more lines since it's much easier to edit CSV than it was for jocs. Closing for now.
