### ISSUE TITLE
Improve failsafe drone bahavior

### ISSUE THREAD

**Issue by tessmichi** [dennisss/tansa#12]
Use timeout behavior. A subprogram on the drone should auto-kill in the following scenarios.
- When messages are timedout or it doesn't get heartbeats from the server.
- When no instance of the software is running (related to previous bullet point)

**Comment by tessmichi** [comment]
Reusing this issue for new task to fix handling loss of motion capture. Must test what currently happens (remember how motion capture is lost and sometimes recovered immediately even in prince production)

**Comment by tessmichi** [comment]
Assigning myself and Dan as discussed in requirements doc meeting

**Comment by dennisss** [comment]
Tested and verified working land failsafe for connection timeout and mocap lose
