### ISSUE TITLE
Drexel - New Workflow Migration

### ISSUE THREAD

**Issue by dennisss** [dennisss/tansa#122]
Tracking the migration to the changes I make yesterday:

Changelog
1. Moved most data files to a separate repo
2. Separated configs:
    - Moved `src/jocsConfig.json` to `config/jocs.json` 
    - Moved `src/config.json` to `config/config.json`
3. To deal with configs and data files in different repos/directories, I've added a `TANSA_PATH` environment variable which, if set, specifies the directory in which the `data/` directory and `config/` directory is located. If a config file does not exist in the `TANSA_PATH`, then it will be grabbed from the default location `./config/*`.

What everyone should do on their local machines:
1. Create a backup of the old code/repo until this version is functional
2. Reclone this repo
3. Clone the `tansa-pdc` repo to an adjacent folder
4. Try running the main program with `TANSA_PATH=../tansa-pdc/ make run`. This should use the data and config files from that repo to populate the gui.

What to do with the lab computer
- Keep the old stable version for now
- Try to clone this new code into a different directory and verify functionality
- The previous `dec2chor` data files are on master of `tansa-pdc`
- Tess's changes from yesterday are available on the `jocsLessDrones` branches of each repo

**Comment by tessmichi** [comment]
Coding team all done setting this up
