### ISSUE TITLE
Fix PR template

### ISSUE THREAD

**Issue by tessmichi** [dennisss/tansa#132]
Add checks for various tests, documentation, signoffs, testing branch verification, and create TEST branch.
Assigning myself as discussed at requirements meeting

**Comment by dennisss** [comment]
A heads up that I've added integration testing to the repo, so any pull request that doesn't pass the tests under the test/ directory or doesn't compile can't be merged.

**Comment by tessmichi** [comment]
Awesome, that'll help too

**Comment by abramowitzK** [comment]
This has been done
