### ISSUE TITLE
Create an Evironment for Mike using Docker

### ISSUE THREAD

**Issue by dmz38** [dennisss/tansa#141]
Create a Linux environment for Mike to be able to run Tansa in on his Mac using Docker.

**Comment by dennisss** [comment]
Environment part of this is done. How to get it running on any computer is documented in the first part of https://github.com/dennisss/tansa/tree/master/config/docker#quickstart . Right now is it precompiled and stored on hub.docker.com for easy distribution, so let me know if it needs to be rebuilt with newer changes for mike
