### ISSUE TITLE
CSV Lighting Specification

### ISSUE THREAD

**Issue by dennisss** [dennisss/tansa#150]
- Mike asked about how to specify lighting yesterday, although there currently isn't a way?
- The simulation viewer is setup to show RGB lights now so this should be easily testable

**Comment by abramowitzK** [comment]
I'll implement lighting today in CSV. I just need to fill in the parsing functions

**Comment by abramowitzK** [comment]
Currently working on  this in csv branch

**Comment by abramowitzK** [comment]
@dennisss  The lights only have RGB channels and no overall intensity values correct? or are they RGBA?

**Comment by abramowitzK** [comment]
@dennisss Do you want me to adapt the currently existing lighting stuff (controller and trajectories) to be used exclusively with rgb drones or should I remain backwards compatible?

**Comment by dennisss** [comment]
Go ahead and change it. Preferably maintain backwards compatibility by just casting single channel values to white/gray, no need to be too fancy

**Comment by abramowitzK** [comment]
Will do. I've got white_strobe and white_light in csv already for old functionality. Will let you know when I'm done so you can review and suggest any changes.

**Comment by abramowitzK** [comment]
Probably wont' be done til friday though. Have to catch up on grading. Depends on how late I stay up...

**Comment by abramowitzK** [comment]
Talked to mike about lighting specification. He is used to composing lighting effects together (Strobe+Fade+Color for example). This is apparently how they do it in the theater world. Working on a good way to replicate this

**Comment by abramowitzK** [comment]
This is partially implemented in csv_lighting branch. In progress.

**Comment by abramowitzK** [comment]
Lighting specification implemented in csv and parser
