### ISSUE TITLE
Server should ensure every position path is differentiable

### ISSUE THREAD

**Issue by tessmichi** [dennisss/tansa#3]
Any discontinuity should result in a fail-safe result if reached. But if #4 is done before running a jocs file, this should never happen.

Should be able to run this check from a specific time along with new "home" locations as well, as described in scenario for #44

**Comment by tessmichi** [comment]
Assigning to Kyle as discussed in Requirements doc

**Comment by abramowitzK** [comment]
We check for temporal and spatial discontinuities upon loading a choreographies.
