### ISSUE TITLE
JOCS v2

### ISSUE THREAD

**Issue by tessmichi** [dennisss/tansa#56]
Includes completion of #83 and #47 and #59 , testing each, and verifying each jocs file abides by same rules and runs without flaw.

Might also require clearing out the jocs files that are more work to maintain than they're worth.

**Comment by tessmichi** [comment]
This wasn't in the list to do this term but is a prereq for one of my tasks

**Comment by abramowitzK** [comment]
Chose to use CSV instead of jocs
