### ISSUE TITLE
Investigate JS frameworks for GUI

### ISSUE THREAD

**Issue by zls29** [dennisss/tansa#89]
Open ended issue, details tbd...

**Comment by tessmichi** [comment]
Assigning to Zach per discussion on Requirements doc

**Comment by dennisss** [comment]
From my experience, I'd recommend React and strongly advise against using anything Angular

**Comment by tessmichi** [comment]
That's the same thing my old boss suggested, and we discussed it very briefly last term.

Also I wanted to add on this issue that we discussed at our meeting possibly adding TypeScript

**Comment by abramowitzK** [comment]
@zls29 we ended up going with React correct? Can we close this issue?

**Comment by zls29** [comment]
Correct, this can be closed once #143 is merged.

**Comment by abramowitzK** [comment]
@zls29 @dennisss  Looks like there are build errors on the CI build that are blocking this from being merged.

**Comment by dennisss** [comment]
Looks like node_modules weren't included in the CI build. My latest commit should hopefully fix it.

**Comment by abramowitzK** [comment]
@dennisss Fixed it. Build just passed. Thanks

**Comment by abramowitzK** [comment]
This has been done.
