### ISSUE TITLE
Control multiple lights per drone

### ISSUE THREAD

**Issue by tessmichi** [dennisss/tansa#90]
Light IDs: Some way to assign light actions to outputs. Top/bottom of each drone

**Comment by tessmichi** [comment]
This is a prerequisite to adding/moving a light, or even just controlling the two lights we used to have separately. As discussed, Kyle will work on this. Kyle, make sure the engineering team is planning on installing these lights this term.

**Comment by abramowitzK** [comment]
This is implemented in CSV
